In [1]:
import numpy as np

In [109]:
class Hoptfield :
    def __init__ (self,n_cells):
        self.n_cells = n_cells
        self.weights = np.mat(np.zeros((n_cells,n_cells)))
        
    def addMemory(self, memory):
        self.weights = self.weights + (memory.T * memory) - np.mat(np.eye(self.n_cells))
        
    def energy(self, state):
        return -1/float(2) * state * self.weights * state.T
        
    def findMinimum(self,state):
        s = state
        for (i in range(0,self.n_cells)):
            np.sign(self.weights[i,:] * state)
            
        self.weights[]
        return 0

In [116]:
hn = Hoptfield(3)
hn.addMemory(np.mat([1,1,1]))
hn.energy(np.mat([1,1,1]))

np.sign(hn.weights[0,:] * hn.weights[0,:].T)

matrix([[ 1.]])

In [102]:
np.shape(np.matrix([1,1,1]))

(1, 3)

In [86]:
v = np.array([1,2,3]) 
v.dot(v.T)

14

In [10]:
eye*np.array([1,2,3])

array([[ 1.,  0.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  3.]])

In [87]:
eye*eye

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [89]:
np.matrix(eye)+np.matrix(eye)

matrix([[ 2.,  0.,  0.],
        [ 0.,  2.,  0.],
        [ 0.,  0.,  2.]])

In [92]:
M = np.matrix(np.zeros((3,3)))
v = np.matrix([1,2,3])
M + (v.T*v) - np.matrix(np.eye(3))

matrix([[ 0.,  2.,  3.],
        [ 2.,  3.,  6.],
        [ 3.,  6.,  8.]])